apiVersion: v1
kind: Pod
metadata:
  name: kube-apiserver
  namespace: kube-system
spec:
  containers:
  - command:
    - /bin/sh
    - -c
    - /usr/local/bin/kube-apiserver
      --token-auth-file=/srv/kubernetes/known_tokens.csv
      --bind-address=192.168.99.104
      --secure-port=443
      --client-ca-file=/srv/kubernetes/ca.crt
      --tls-cert-file=/srv/kubernetes/server.crt
      --tls-private-key-file=/srv/kubernetes/server.key
      --admission-control=ServiceAccount
      --advertise-address=192.168.99.104
      --etcd-servers=http://192.168.99.101:2379,http://192.168.99.102:2379,http://192.168.99.103:2379
      --cloud-provider=unset
      --service-cluster-ip-range=10.0.0.0/16
      --allow-privileged=True
      1>>/var/log/k8s/kube-apiserver.log 2>&1
    image: gcr.io/google_containers/kube-apiserver:5a24975398aa6a912695413b8acb65a8
    imagePullPolicy: IfNotPresent
    livenessProbe:
      httpGet:
        host: 127.0.0.1
        path: /healthz
        port: 8080
        scheme: HTTP
      initialDelaySeconds: 15
      timeoutSeconds: 15
    name: kube-apiserver
    ports:
    - containerPort: 8080
      hostPort: 8080
      name: http
      protocol: TCP
    - containerPort: 443
      hostPort: 443
      name: https
      protocol: TCP
    resources:
      requests:
        cpu: 250m
    volumeMounts:
    - mountPath: /srv/kubernetes
      name: srvkube
      readOnly: true
    - mountPath: /var/log/k8s
      name: logfile
    - mountPath: /etc/ssl
      name: etcssl
      readOnly: true
    - mountPath: /usr/share/ca-certificates
      name: usrsharecacerts
      readOnly: true
    - mountPath: /srv/sshproxy
      name: srvsshproxy
  dnsPolicy: ClusterFirst
  hostNetwork: true
  restartPolicy: Always
  terminationGracePeriodSeconds: 30
  volumes:
  - hostPath:
      path: /srv/kubernetes
    name: srvkube
  - hostPath:
      path: /var/log/k8s
    name: logfile
  - hostPath:
      path: /etc/ssl
    name: etcssl
  - hostPath:
      path: /usr/share/ca-certificates
    name: usrsharecacerts
  - hostPath:
      path: /srv/sshproxy
    name: srvsshproxy